name: Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET Framework
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Setup NuGet
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: 'latest'
        
    - name: Restore NuGet packages
      run: nuget restore
      
    - name: Build solution
      run: msbuild /p:Configuration=Release /p:Platform="Any CPU"
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: DesktopPet-Release
        path: |
          Pet.UI/bin/Release/
          !Pet.UI/bin/Release/*.pdb
          !Pet.UI/bin/Release/*.xml
